# Generated by Django 3.2.13 on 2022-05-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.CharField(max_length=200)),
                ('itemA', models.CharField(max_length=100)),
                ('itemB', models.CharField(max_length=100)),
                ('itemC', models.CharField(max_length=100)),
                ('itemD', models.CharField(max_length=100)),
                ('itemE', models.CharField(max_length=100)),
                ('gabarito', models.CharField(max_length=1)),
                ('eixo', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('subcategoria', models.CharField(max_length=100)),
            ],
        ),
    ]
