# Generated by Django 3.2.13 on 2022-05-27 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questoes',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='questoes',
            name='eixo',
        ),
        migrations.RemoveField(
            model_name='questoes',
            name='subcategoria',
        ),
    ]
