# Generated by Django 3.2.13 on 2022-05-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_classificacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificacaoAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eixo', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('subcategoria', models.CharField(max_length=100)),
            ],
        ),
    ]
