# Generated by Django 3.2.13 on 2022-05-27 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_questao_classificacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questao_Classificacao',
        ),
    ]
