# Generated by Django 3.2.13 on 2022-05-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_questoes_id_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questoes',
            name='gabarito',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1),
        ),
    ]
