# Generated by Django 3.2.13 on 2022-05-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_historico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questoes',
            name='enunciado',
            field=models.TextField(),
        ),
    ]
