# Generated by Django 3.2.13 on 2022-05-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_questoes_enunciado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questoes',
            name='itemA',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='questoes',
            name='itemB',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='questoes',
            name='itemC',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='questoes',
            name='itemD',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='questoes',
            name='itemE',
            field=models.CharField(max_length=500),
        ),
    ]
