# Generated by Django 3.2.13 on 2022-05-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20220530_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questoes',
            name='itemA',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questoes',
            name='itemB',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questoes',
            name='itemC',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questoes',
            name='itemD',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questoes',
            name='itemE',
            field=models.TextField(),
        ),
    ]
