# Generated by Django 4.0.4 on 2022-06-29 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20220530_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historico',
            old_name='id_questao',
            new_name='questao',
        ),
        migrations.RenameField(
            model_name='questoes',
            old_name='id_class',
            new_name='classificacao',
        ),
    ]
